prod:
  children:
    sys:
      hosts:
        prod-sys:
          ansible_become: true
    app:
      hosts:
        prod-app:
  vars:
    ansible_connection: ssh
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3.12

