hosts:
  hosts:
    main:
      ansible_host: prod-sys
      ansible_connection: ssh
      ansible_become: true
      ansible_become_method: sudo
      ansible_python_interpreter: /usr/bin/python3.12

