- hosts: localhost
  connection: local

  tasks:
    - name: Packages
      become: true
      ansible.builtin.package:
        name:
          - docker

    - name: Add .ssh/
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: "0700"

    - name: Generate SSH sys key
      community.crypto.openssh_keypair:
        path: ~/.ssh/prod-sys
        type: ed25519

    - name: Generate SSH app key
      community.crypto.openssh_keypair:
        path: ~/.ssh/prod-app
        type: ed25519

    - name: Add SSH config
      ansible.builtin.blockinfile:
        create: true
        path: ~/.ssh/config
        mode: "0600"
        block: |
          Host prod-sys
            User {{ prod.user_sys }}
            HostName {{ prod.host }}
            IdentityFile ~/.ssh/prod-sys

          Host prod-app
            User {{ prod.user_app }}
            HostName {{ prod.host }}
            IdentityFile ~/.ssh/prod-app
